
#-------------------------------------------------------------
#author:ANUSHKA GUPTA




#-------------------------------------------------------------
# Strings
# Strings in python are surrounded by either single quotation marks, or double quotation marks.

# 'hello' is the same as "hello".

# You can display a string literal with the print() function:



# Multiline Strings
# You can assign a multiline string to a variable by using three quotes:


# Slicing
# You can return a range of characters by using the slice syntax.

# Specify the start index and the end index, separated by a colon, to return a part of the string.


# Negative Indexing
# Use negative indexes to start the slice from the end of the string:


# Python - Modify Strings
# Python has a set of built-in methods that you can use on strings.

# Upper Case
# Example
# The upper() method returns the string in upper case:

# a = "Hello, World!"
# print(a.upper())
# Lower Case
# Example
# The lower() method returns the string in lower case:

# a = "Hello, World!"
# print(a.lower())
# Remove Whitespace
# Whitespace is the space before and/or after the actual text, and very often you want to remove this space.

# Example
# The strip() method removes any whitespace from the beginning or the end:


#String Methods
#Python has a set of built-in methods that you can use on strings.

#Note: All string methods returns new values. They do not change the original string.

#Method	Description
#capitalize()		Converts the first character to upper case
#casefold()		Converts string into lower case
#center()		Returns a centered string
#count()		Returns the number of times a specified value occurs in a string
#encode()	Returns an encoded version of the string
#endswith()	Returns true if the string ends with the specified value
#expandtabs()	Sets the tab size of the string
#find()		Searches the string for a specified value and returns the position of where it was found
#format()	Formats specified values in a string
#format_map()	Formats specified values in a string
#index()	Searches the string for a specified value and returns the position of where it was found
#isalnum()	Returns True if all characters in the string are alphanumeric
#isalpha()	Returns True if all characters in the string are in the alphabet
#isdecimal()	Returns True if all characters in the string are decimals
#isdigit()	Returns True if all characters in the string are digits
#isidentifier()	Returns True if the string is an identifier
#islower()	Returns True if all characters in the string are lower case
#isnumeric()	Returns True if all characters in the string are numeric
#isprintable()	Returns True if all characters in the string are printable
#isspace()	Returns True if all characters in the string are whitespaces
#istitle()	Returns True if the string follows the rules of a title
#isupper()	Returns True if all characters in the string are upper case
#join()	Joins the elements of an iterable to the end of the string
#ljust()	Returns a left justified version of the string
#lower()	Converts a string into lower case
#lstrip()	Returns a left trim version of the string
#maketrans()	Returns a translation table to be used in translations
#partition()	Returns a tuple where the string is parted into three parts
#replace()	Returns a string where a specified value is replaced with a specified value
#rfind()	Searches the string for a specified value and returns the last position of where it was found
#rindex()	Searches the string for a specified value and returns the last position of where it was found
#rjust()	Returns a right justified version of the string
#rpartition()	Returns a tuple where the string is parted into three parts
#rsplit()	Splits the string at the specified separator, and returns a list
#rstrip()	Returns a right trim version of the string
#split()	Splits the string at the specified separator, and returns a list
#splitlines()	Splits the string at line breaks and returns a list
#startswith()	Returns true if the string starts with the specified value
#strip()	Returns a trimmed version of the string
#swapcase()	Swaps cases, lower case becomes upper case and vice versa
#title()	Converts the first character of each word to upper case
#translate()	Returns a translated string
#upper()	Converts a string into upper case
#zfill()	Fills the string with a specified number of 0 values at the beginning

#x="Arunachal pradesh"
#print(len(x))
#print(x[5])
#print(x[-4])


#return second item
#print(x[2])
#return 17th item
#print(x[16])
#return 12 item
#print(x[12])
#return fourth item
#print(x[4])
#return 3rd item
#print(x[3])
#return 15th item
#print(x[15])
#return 1st item
#print(x[1])
#return second item
#print(x[2])
#return ninth item'''
#print(x[9])

#////////////////////////////////////////////////////////////////////////////

#////////////////////////////////////////////////////////////////////////////


'''x="hello delhi"
print(x[0:5])
print(x[-11:-6])
print(x[6])
print(x[-5])'''

'''x="Himachal pradesh"		# 0  1  2  3  4  5  6  7 8 9 10 11 12  13 14 15
print(len(x))				# H  i  m  a  c  h  a  l   p  r  a  d  e  s  h
print(x[3])
print(x[-14])					#
print(x[4])
print(x[-13])
print(x[5])
print(x[-12])
print(x[3:15])
print(x[-14:]






