
#-------------------------------------------------------------
#author:ANUSHKA GUPTA




#-------------------------------------------------------------
# Strings
# Strings in python are surrounded by either single quotation marks, or double quotation marks.

# 'hello' is the same as "hello".

# You can display a string literal with the print() function:



# Multiline Strings
# You can assign a multiline string to a variable by using three quotes:


# Slicing
# You can return a range of characters by using the slice syntax.

# Specify the start index and the end index, separated by a colon, to return a part of the string.


# Negative Indexing
# Use negative indexes to start the slice from the end of the string:


# Python - Modify Strings
# Python has a set of built-in methods that you can use on strings.

# Upper Case
# Example
# The upper() method returns the string in upper case:

# a = "Hello, World!"
# print(a.upper())
# Lower Case
# Example
# The lower() method returns the string in lower case:

# a = "Hello, World!"
# print(a.lower())
# Remove Whitespace
# Whitespace is the space before and/or after the actual text, and very often you want to remove this space.

# Example
# The strip() method removes any whitespace from the beginning or the end:
